### ISSUE TITLE
Logo Proposal.

### ISSUE THREAD

**Issue by mendezand** [Madonahs/Devsfolio#141]
Hi.

If necessary I can work on a logo for Devsfolio.
I will be attentive to your answer.

Greetings.

**Comment by Madonahs** [comment]
Hey, how are you? sorry i have been busy with my other project i bet this passed me. Thank you very much for wanting to create one for us, however we do have one already in use. 👍 I appreciate your need to help.

**Comment by mendezand** [comment]
A pleasure.
