### ISSUE TITLE
Issue with Firebase

### ISSUE THREAD

**Issue by emmaunel** [Madonahs/Devsfolio#151]
It seems that our firebase can't be accessed anymore(well, the data we stored). I don't know how or why but I can't log in anymore.
Also if you go to the firebase console, our data is gone and it shows an error at the top right.

**To Reproduce**
Log out if you are currently logged in.
Now try logging in again.
You should receive a toast error.

**Expected behavior**
The error message I got is: "An internal error has occurred. [ API key not valid. Please pass a valid API key ]

**Comment by Madonahs** [comment]
@emmaunel I think @MaherSoua  deleted the Database without informing the team which is mean instead of transferring it, but I did create one and we can use this one. 👍 Let me send you details.

**Comment by MaherSoua** [comment]
I am really sorry, I managed my project for Google api and deleted all
project and recreate them, I didn't know that you use my workspace, I
thought that you change it for a while.

**Comment by emmaunel** [comment]
It's fine

**Comment by Madonahs** [comment]
@MaherSoua It is okay.  I appreciate your apology. Accepted. 👍  Hope you are doing great. Did you manage to launch your amazing App? I could tell it was awesome when you shared the images.

**Comment by MaherSoua** [comment]
Hi @madona, thanks I hope you do great too, as I am involving in the
development, I think that I will redo some part of it and improve it, I had
some lagging issue when scrolling I have to fix this too.
